server:
  port: 80
  servlet:
    context-path: /accountmanagement
spring:
  datasource:
    url: jdbc:mysql://localhost/account?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      maximum-pool-size: 8
  redis:
    host: localhost
    port: 6379
    password:
  cache:
    redis:
      key-prefix: redisCache::$
      time-to-live: 86400000
mybatis:
  mapper-locations: mapper/*.xml
  lazy-initialization: true
  configuration:
    database-id: mysql
logging:
  level:
    org.gonnaup.accountmanagement.dao: info
    org.gonnaup.accountmanagement.web: debug
dubbo:
  application:
    name: dubbo-accountmanagement
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: multicast://224.5.6.7:1234